### ISSUE TITLE
Attending event on somebody else's behalf

### ISSUE THREAD

**Issue by wfdd** [popolo-project/popolo-spec#119]
While parsing the Cypriot parliament's committee reports, I'd often find that non-members would attend committee meetings on a committee member's behalf, the latter - presumably - being away on official business.  (The exact wording they use is "X, representing Y".)  Seeing as `attendees` is a list of `Person`s, I don't suppose there's currently a way to express this relationship in Popolo.  In general, it'd be useful to note when somebody attends an event in their capacity as a member of the organising organisation; as representing another member; or as a non-member.

**Comment by jpmckinney** [comment]
Yes, this happens in some US states as well. One option is to have an intermediate Attendance object between the Event and the Person - like how Membership is an intermediate object between Organization and Person. However, the case of people attending as themselves is so overwhelmingly common that I wouldn't want to make that common case more complicated.

Another option is to instead add a note on the event (instead of adding a note on an intermediate Attendance object) along the lines of "X is representing Y". This model is more complicated for the less common case where people attend on another's behalf.

What do you think?

**Comment by wfdd** [comment]
A free-form note?  That sounds unideal; I'd rather be able to explicitly tie a `Person` to their attendance 'mode'.  I mean - we'll have packaged the information, but we'll have failed to encode it.

**Comment by jpmckinney** [comment]
The note can be more structured. I don't mean using the note property that some classes have.

**Comment by wfdd** [comment]
Okay, so we'd basically be listing some people in two different places.  That works I suppose.

**Comment by jpmckinney** [comment]
Yes, it would be a compromise between having a little more duplication in rare cases and having a lot more complexity in common cases.

**Comment by wfdd** [comment]
Something like this then?

``` yaml
attendance_details:
  - attendee_id: politician/a
    on_behalf_of_id: politician/b
```

... where items would be defined as:

``` yaml
properties:
  attendee_id:
    type: [string, 'null']
  attendee:
    $ref: http://www.popoloproject.com/schemas/person.json#
  on_behalf_of_id:
    type: [string, 'null']
  on_behalf_of:
    $ref: http://www.popoloproject.com/schemas/person.json#
  note:
    type: [string, 'null']
```

Thoughts?
